.travis.yml, composer.json, src/Handler/AddPrefixCommandHandler.php, tests/Fixtures/replaced/dir/dir/MySecondClass.php, tests/Fixtures/replaced/dir/dir/MyThirdClass.php, tests/Handler/AddPrefixCommandHandlerTest.php, tests/PhpScoperTest.php, tests/ScoperTest.php
Does what it says on the tin ;). Allows composer to install correctly; gets tests to passing state.
A few test updates add additional spaces to fixtures used as expected output. I'll leave it as separate exercise to see where those are added, and if they can be conditionally omitted.
Note: Updated Appveyor config and extended separately with #17. The failure at present is just choco needing Windows Update to run for its missing deps.
=> Update dependencies and tests

LICENSE, README.md, composer.json
Enabled access for Travis, Appveyor and Scrutinizer to the project. Updated links and references in files mentioned. I'd like to keep webmozart mentioned reasonably prominently in the README for credit (without it prompting support queries to him). I also added everyone as a "Developer" with access to the Scrutinizer account for our main repos.
Note: I provisionally added myself and Theo to the License copyright term (post 2016). Theo, I have no objections to just leaving you as the sole name after Bernhard since php-scoper being here is entirely your suggestion (so you should take the blame for it ;)).
=> README, composer.json, LICENSE edits for transfer to Humbug

appveyor.yml
- Extends PHP versions to test against.
- Enables Windows Update (choco depends on updates some of the time).
- Not sure about x86 vs x64, so assumed a modern system and switched.
- Enabled caching to speed up builds.
Note: Build will fail pending #16.
=> Update Appveyor config; test for PHP 5.6, 7.0, 7.1

.styleci.yml
"The provided fixer 'empty_return' cannot be disabled unless it was already enabled by your preset."
=> Fix StyleCI misconfiguration

src/Handler/HandleAddPrefix.php, tests/Handler/HandleAddPrefixTest.php
- Throws an error when a path given is invalid (file/directory does not exist)
- Non PHP files are copied as well (but are not parsed or changed)
- Throw a more meaningful error when the parsing of a file fails (give the file path)
=> Handle non-existent files and non PHP files

tests/Console/Command/AddPrefixCommandIntegrationTest.php
I'm not sure what PhpStorm was doing neither how it works on Travis, but the tests are failing on my machine because of those trailing spaces.
=> Fix PHPUnit

src/NodeVisitor/FullyQualifiedNamespaceUseScoperNodeVisitor.php, src/NodeVisitor/IgnoreNamespaceScoperNodeVisitor.php, tests/Scoper/PhpScoperTest.php
Also fix unrelated bug stripping `\` from start of FQN after concatenating prefixes
closes #53
=> Properly scope fully-qualified class name nodes

src/NodeVisitor/IgnoreNamespaceScoperNodeVisitor.php
Minor bug - doesn't cause a problem right now because it is overlapped by `GroupUse` check in `UseNamespaceScoperNodeVisitor`.
=> Use statement omission

src/NodeVisitor/ClassExistsScoperNodeVisitor.php, src/NodeVisitor/FunctionCallScoperNodeVisitor.php, src/Scoper/PhpScoper.php, tests/Scoper/PhpScoperTest.php
We should support `class_exists('\\Symfony\\Component\\Yaml\\Yaml')`. 
(Im having some issues running this lib over Symfony code base.)
This will fix #73
=> Add support for class_exists('string')

phpunit.xml.dist, src/Scoper/Composer/InstalledPackagesScoper.php, tests/Console/Command/AddPrefixCommandIntegrationTest.php, tests/Scoper/Composer/InstalledPackagesScoperTest.php, tests/Scoper/Composer/JsonFileScoperTest.php, tests/Scoper/PatchScoperTest.php
- Remove useless code
- Whitelist code that should not be unit tested (they are covered by integration tests)
- Add missing tests
=> Fix PHPUnit coverage

.gitignore, Makefile, composer.json, composer.lock, phpunit.xml.dist, src/Console/Command/SelfUpdateCommand.php, src/Logger/UpdateConsoleLogger.php, src/functions.php, vendor-bin/box/composer.json, vendor-bin/box/composer.lock
Implements #45 
Assumes using Github releases to host a signed phar.
=> Add a basic SelfUpdateCommand using phar-updater v1

src/Scoper/PhpScoper.php, src/Scoper/TraverserFactory.php, src/functions.php, tests/Scoper/PhpScoperTest.php, tests/Scoper/TraverserFactoryTest.php
As the traverser is now stateful, even though it won't break things
as the code is robust enough right now, it severely impacts performances.
For example, the collection of namespace was kept which led to a lot of
namespaces at some point forcing the NamespaceCollection to go through
the node parents to find the proper namespace, even though only one
namespace was found in the file.
=> Make traverser return a new instance for each file

Makefile
- More robust rules to ensure any command works properly in any situation
- Do not rebuild the PHAR if already exists
- Do not erase PHPStorm settings when doing a `make clean`
=> Various Makefile tweaks

.travis.yml
Builds for PRs are currently failing due to being unable to decrypt encrypted files. Indeed the secured files are bound to this repository so this cannot work for fork builds which are bound to the fork repository.
See https://github.com/pockethub/PocketHub/issues/884 for more
=> Fix Travis build for PRs

.styleci.yml
Added the desired StyleCI disables to remove the checks on property separation and const separation.
This will prevent the check from failing.
=> StyleCI: new line checks

src/Console/Command/AddPrefixCommand.php, src/Scoper.php, src/Scoper/Composer/InstalledPackagesScoper.php, src/Scoper/Composer/JsonFileScoper.php, src/Scoper/NullScoper.php, src/Scoper/PatchScoper.php, src/Scoper/PhpScoper.php, tests/Console/Command/AddPrefixCommandTest.php, tests/Scoper/Composer/InstalledPackagesScoperTest.php, tests/Scoper/Composer/JsonFileScoperTest.php, tests/Scoper/FakeScoper.php, tests/Scoper/NullScoperTest.php, tests/Scoper/PatchScoperTest.php, tests/Scoper/PhpScoperTest.php
Continuing some work for humbug/box#31. The Scoper now takes the file contents as an argument. This allows the scoper to be used with existent files (e.g. virtual files) or files for which we are modifying the content like in Box.
Another benefit is that it removes the Scopers dependency to the file system layer.
=> Add file contents to the Scoper

src/Scoper/PhpScoper.php, src/functions.php, tests/Scoper/PhpScoperTest.php
As now we have access to the content of the file, we can also check if a file is a PHP file based on its content. This ensure binary PHP files are scoped.
Also did a small refactoring regarding the order of the scopers registered for a micro-optimisation.
=> Properly parse binaries

specs/function/global-scope-global-func-with-single-level-use-statement-and-alias.php, specs/function/global-scope-global-func-with-single-level-use-statement.php, specs/function/global-scope-global-func.php, specs/function/namespace-global-func-with-single-level-use-statement-and-alias.php, specs/function/namespace-global-func-with-single-level-use-statement.php, specs/function/namespace-global-func.php, specs/function/namespace-global-scope-func.php, specs/use/use-func.php, src/NodeVisitor/NameStmtPrefixer.php, src/NodeVisitor/UseStmt/UseStmtPrefixer.php, src/Reflector.php, src/functions.php, tests/Scoper/PhpScoperTest.php, tests/Scoper/TraverserFactoryTest.php
Now prefix functions whenever possible. A function is not prefixed when is an internal function or when the function fully qualified name could not be resolved.
Related to #152.
Closes #145.
The failure on the e2e tests is unrelated.
=> Fix prefixing of functions

specs/const/global-scope-global-with-single-level-use-statement-and-alias.php, specs/const/global-scope-global-with-single-level-use-statement.php, specs/const/global-scope-global.php, specs/const/namespace-global-with-single-level-use-statement-and-alias.php, specs/const/namespace-global-with-single-level-use-statement.php, specs/const/namespace-global.php, specs/use/use-const.php, src/NodeVisitor/NameStmtPrefixer.php, src/NodeVisitor/UseStmt/UseStmtPrefixer.php, src/Reflector.php
Prefix the constants whenever possible, i.e. when the constant is not internal.
=> Prefix constants

Makefile, fixtures/set020-infection/scoper.inc.php
Infection was "passing" only because the process was failing hard which indeeds counts as killing a mutant, but in this specific case this was not for the right reasons.
I investigated and managed to apply the right patches to make it work. The e2e tests also no runs the not prefixed Infection and compares the result with the prefixed one as they should be identical.
=> Fix Infection tests

.gitignore, .travis.yml, Makefile
Tweak the Makefile rules to run the same tests twice
=> Re-use coverage

Makefile, fixtures/set011/scoper.inc.php, fixtures/set011/src/Dictionary.php, fixtures/set011/src/DirectionaryLocator.php, fixtures/set011/tests/SalutationDictionary.php, src/Autoload/ScoperAutoloadGenerator.php
Closes #188.
The current mechanism works fine since the `class_exists()` is here only to trigger the autoload.
Since the autoloading mechanism is the same for classes and interfaces, `class_exists()` works fine.
=> Ensure the whitelist feature works well on interfaces

src/Scoper/Composer/AutoloadPrefixer.php, src/Scoper/Composer/InstalledPackagesScoper.php, src/Scoper/Composer/JsonFileScoper.php, tests/Scoper/Composer/InstalledPackagesScoperTest.php, tests/Scoper/Composer/JsonFileScoperTest.php
The JSON files should be decode with `assoc` set to true. Otherwise encoding it again may change the schema as if `assoc` is set to false, both `[]` and `{}` will be decoded as an empty array so
encoding it again may change an empty object into an empty array which may screw up a JSON schema validation.
=> Fix the scoping of JSON files

specs/string-literal/define.php
Closes #209
The remaining cases are checked by the other tests in `specs/string-literal/`
=> Ensure string literals in define statements are properly prefixed

README.md
Use correct representation of empty string, removed duplicated word.
=> Fixed docs about prefixing

README.md, src/Configuration.php, src/Console/ApplicationFactory.php, src/Console/Command/AddPrefixCommand.php, src/Scoper/ConfigurableScoper.php, src/Scoper/FileWhitelistScoper.php, src/scoper.inc.php.tpl, tests/Scoper/FileWhitelistScoperTest.php
=> Add files whitelist feature

specs/const/const-declaration-with-global-whitelisting.php, specs/const/const-declaration.php, specs/function/global-scope-global-func-with-single-level-use-statement-and-alias.php, specs/function/global-scope-global-func.php, specs/function/global-scope-single-part-namespaced-func.php, specs/function/namespace-global-func-with-single-level-use-statement-and-alias.php, specs/function/namespace-global-func-with-single-level-use-statement.php, specs/function/namespace-global-func.php, specs/function/namespace-global-scope-func.php, specs/function/namespace-single-part-namespaced-func.php, specs/function/whitelist-func-existence-checked.php, specs/function/whitelist-func-used.php, specs/string-literal/func-arg.php, src/PhpParser/NodeVisitor/Collection/NamespaceStmtCollection.php, src/PhpParser/NodeVisitor/FunctionIdentifierRecorder.php, src/PhpParser/NodeVisitor/Resolver/FullyQualifiedNameResolver.php, src/PhpParser/TraverserFactory.php, tests/Scoper/PhpScoperSpecTest.php
Previously, if you had the following code:
```php
namespace Acme;
if (function_exists('foo')) {
\foo();
}
```
with `foo` being in the whitelist, the function would have not been whitelisted. The reasoning was that the recording of whitelisted elements was the same for functions and classes. For classes, it makes sense since the whitelisting will not work if the whitelisted class declaration is not found, however this is not the case for functions since the declaration dumped in the `scoper-autoload.php` is sufficient.
With this PR, the function `foo` above is now prefixed, which should allow cases like [this one](https://github.com/humbug/box/issues/193#issuecomment-431915508) to work out of the box, either by whitelisting the global functions or by manually whitelisting it.
=> Whitelist functions as soon as they are used

.scrutinizer.yml, tests/Console/Command/AddPrefixCommandTest.php
Remove the unnecessary run in separate process PHPUnit annotation for the `AddPrefixCommand` unit test and ignore `integration` (the PHPUnit group) tests.
=> Fix running the tests with phpdbg

specs/eval.php, src/PhpParser/NodeVisitor/EvalPrefixer.php, src/PhpParser/NodeVisitor/NewdocPrefixer.php, src/PhpParser/StringScoperPrefixer.php, src/PhpParser/TraverserFactory.php
Attempt to scope the content of the eval function whenever possible. Leave the expression unchanged
otherwise.
=> Add support for the eval function

fixtures/set016-symfony-finder/main.php, fixtures/set023/expected-output, fixtures/set023/main.php, src/Autoload/ScoperAutoloadGenerator.php, src/Scoper/Composer/InstalledPackagesScoper.php, src/functions.php, tests/ConfigurationTest.php, tests/Console/Command/AddPrefixCommandIntegrationTest.php, tests/Console/DisplayNormalizer.php, tests/FunctionsTest.php
Fix #122 .
I still have 3 errors but I don't know if it's related to Windows.
The details of the errors:
```
1) Humbug\PhpScoper\Console\Command\AddPrefixCommandIntegrationTest::test_scope_in_normal_mode
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in C:\Users\villfa\AppData\Local\Temp\PHP3EBD.tmp:254
Stack trace:
#0 C:\Users\villfa\AppData\Local\Temp\PHP3EBD.tmp(254): serialize(Array)
#1 C:\Users\villfa\AppData\Local\Temp\PHP3EBD.tmp(730): __phpunit_run_isolated_test()
#2 {main}
thrown in C:\Users\villfa\AppData\Local\Temp\PHP3EBD.tmp on line 254
Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in C:\Users\villfa\AppData\Local\Temp\PHP3EBD.tmp:254
Stack trace:
#0 …
```
=> Fix unit tests for Windows

src/scoper.inc.php.tpl
The key `whitelist-global-constants` was found twice. I replaced one of them to be `whitelist-global-classes`.
=> Fixed duplicate key found in scoper.inc.php.tpl

.composer-root-version, .gitignore, .travis.yml, Makefile, bin/check-composer-root-version.php, bin/dump-composer-root-version.php, bin/root-version.php
Since PHP-Scoper depends (as a dev dep) on Box which itself depends on PHP-Scoper, the
`COMPOSER_ROOT_VERSION` environment variable must be set accordingly for Composer.
Until now, the value was hardcoded in a few places and manually updated. It's however causing a number of issues since:
- It requires to manually check that the value set is the correct one by checking the last tag release
- It requires to manually update the values (find/replace in an IDE or other)
Since I'm a bit forgetful, this is messing up things occasionally.
In order to tackle this issue, this PR introduces a:
- `.composer-root-version` file committed which exports the right `COMPOSER_ROOT_VERSION` value
- Replaces the hardedcoded occurrences of `COMPOSER_ROOT_VERSION` by loading the newly introduced …
=> Automatically check the COMPOSER_ROOT_VERSION

bin/php-scoper, box.json.dist, src/Console/Application.php, src/Console/ApplicationFactory.php, src/Container.php, src/functions.php, tests/Console/Command/AddPrefixCommandTest.php, tests/ContainerTest.php, tests/functions.php
- Introduce a `Container` class instead of relying on the `ApplicationFactory`
- Simplify the Application version retrieval
- Move the code in a `get_php_scoper_version(): string` similar to `get_box_version(): string`
- Retrieve the version from it if no version is passed
- No longer rely on a version set within the PHAR
- Remove the deprecated `create_scoper()` function
=> Introduce a container

bin/php-scoper, src/Autoload/ScoperAutoloadGenerator.php, src/functions.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
=> Add a guard before loading the whitelisted classes

Makefile, scoper.inc.php
Closes #368
Turns out the end-to-end test was not working as expected because was using the `bin/php-scoper` directly instead of the PHAR as it should
=> Fix isolated finder

README.md
The link was (box) instead of [box] so it was broken
=> Fixed link to Box

tests/Scoper/ConfigurableScoperTest.php, tests/Scoper/FileWhitelistScoperTest.php, tests/Scoper/PatchScoperTest.php, tests/Scoper/PhpScoperTest.php, tests/Scoper/Symfony/XmlScoperTest.php, tests/Scoper/Symfony/YamlScoperTest.php
- According to the [PHPUnit fixtures reference](https://phpunit.readthedocs.io/en/8.5/fixtures.html?highlight=fixtures), it should be `protected setUp` method.
=> Imrove PHPUnit fixtures

specs/misc/name-resolution.php, src/PhpParser/NodeVisitor/UseStmt/UseStmtCollection.php
=> Fix naming resolution issue

src/Scoper/Composer/InstalledPackagesScoper.php, tests/Scoper/Composer/InstalledPackagesScoperTest.php
The format of `installed.json` has changed in Composer v2. See:
https://github.com/composer/composer/blob/56811b4c8fec9c2eda5bd47a2c079e121c668eb4/src/Composer/Repository/FilesystemRepository.php#L72-L75
=> Fix InstalledPackagesScoper with Composer v2

.travis.yml, composer.json, composer.lock
*php-scoper* cannot be installed with Composer 2 (see below). [More details here](https://github.com/composer/package-versions-deprecated/blob/master/README.md).
```
$ git clone https://github.com/humbug/php-scoper && cd php-scoper
[...]
$ composer --version
Composer version 2.0.0-alpha2 2020-06-24 21:36:18
$ COMPOSER_ROOT_VERSION='0.13.99' composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
Problem 1
- ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
- ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] …
```
=> Add compatibility with Composer 2

fixtures/set011/composer.json, fixtures/set011/polyfill/Iterator.php, src/Autoload/ScoperAutoloadGenerator.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
Only performing `class_exists()` is not sufficient as interfaces and
traits are different kind of autoloadable things.
Therefore we have to test that none of these exist prior trying to
autoload an alias them.
Fixes #403
=> Also check for interfaces and traits in existence checks

.github/workflows/build.yml
I read about the issue #419 that phar files were not uploaded for the latest releases. This might be an issue with travis so I was wondering if GitHub Actions could be a solution.
=> Enabling GitHub Actions as CI + phar uploading on releases

README.md
Documentation says that `class_exists()` is used to autoload the aliased class, but `class_alias()` is used in the example.
=> Correct function in docs

.github/workflows/build.yml, .github/workflows/lint.yml, Makefile, phpcs.xml.dist, vendor-bin/code-sniffer/composer.json, vendor-bin/code-sniffer/composer.lock, vendor-bin/phpstan/composer.json, vendor-bin/phpstan/composer.lock
resolves #430 
This adds linter workflow jobs for php_codesniffer and phpstan.
phpstan is added via the composer bin plugin instead of using wget.
=> adds lint workflow for phpstan and phpcs

composer.lock, specs/exp/coalescing-assignment.php, specs/func-arrow/global-scope-arrow-func.php, specs/func-arrow/namespace-arrow-func-with-use-stmt.php, specs/func-arrow/namespace-arrow-func.php, specs/misc/match.php, src/Container.php, src/Reflector.php, tests/ReflectorTest.php, tests/Scoper/PhpScoperSpecTest.php
=> Add versions to hot-patched symbols

composer.lock
This PR updates symfony to the latest 4.4.16 version.
Symfony 5 support will come in an other PR.
```
- Updating symfony/polyfill-php80 (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/polyfill-php73 (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/console (v4.4.11 => v4.4.16): Loading from cache
- Updating symfony/polyfill-ctype (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/filesystem (v4.4.11 => v4.4.16): Loading from cache
- Updating symfony/finder (v4.4.11 => v4.4.16): Loading from cache
- Updating symfony/process (v4.4.11 => v4.4.16): Loading from cache
- Updating symfony/polyfill-php72 (v1.18.1 => v1.20.0): Loading from cache
- Updating symfony/var-dumper (v4.4.11 => …
```
=> update symfony dependencies

Makefile, src/Container.php, src/Reflector.php, tests/ReflectorTest.php
I was wrong with the Reflector approach. It will prevent us scoping the php-parser.
It is related to https://github.com/box-project/box/pull/499
=> Revert "Add versions to hot-patched symbols" but keep fixed Lexer

src/Console/Command/AddPrefixCommand.php, src/PhpParser/NodeVisitor/StringScalarPrefixer.php, src/Scoper/Composer/InstalledPackagesScoper.php, src/Scoper/Composer/JsonFileScoper.php, src/Scoper/PhpScoper.php, src/Scoper/Symfony/XmlScoper.php, src/Scoper/Symfony/YamlScoper.php, src/Whitelist.php
It can be that the string being matched is not a valid UTF-8 string in which case with the safe extension an exception will be thrown since we want to match it against a regex with unicode support.
In the case of PHP-Scoper though, I am not entirely sure if it's relevant: it can be that PHP-Scoper is scoping non-UTF8 files in general. I am however not sure if it's working at all and rather than introducing more code that is supposed to help this scenario, I would prefer a proper support to be introduced where the use case is clear and proper tests can be added
=> Use native preg_match functions

scoper.inc.php
I believe the following is the canonical way to handle Symfony polyfills. It is however but a workaround and it would be great to be able to figure out a better solution. For those who want to continue the discussion, please head to https://github.com/humbug/php-scoper/issues/440
=> Fix Polyfills

src/Console/Application.php, src/Console/Command/AddPrefixCommand.php, src/Console/Command/ChangeableDirectory.php, src/Console/Command/InitCommand.php, src/Console/ConsoleScoper.php, src/Container.php, src/ScoperFactory.php, tests/Console/Command/AddPrefixCommandTest.php, tests/Console/Command/DummyScoperFactory.php
Related to #303, this will allow to enrich the configuration and forward options from the configuration to the scoper itself, e.g. to inject the native symbols.
**BC Breaks**:
- `Container::getScoper()` has been replaced by `Container::getScoperFactory()`
=> Introduce ScoperFactory

src/ConfigurationFactory.php, src/ConfigurationKeys.php, src/scoper.inc.php.tpl, tests/ConfigurationFactoryTest.php, tests/ConfigurationKeysTest.php, tests/Scoper/PhpScoperSpecTest.php, tests/TemplateFileTest.php
This allows for easier re-use of the configuration keys and add complementary tests to better avoid introducing issues when adding/changing/removing a new config entry.
=> Extract configuration keys into a dedicated enum

composer.json, src/Reflector.php
Split of https://github.com/humbug/php-scoper/pull/535
Fixes PHP 8.1 introduced native constants that should not be prefixed
=> [fix] bump php-parser to 4.12 and fix PHP 8.1 constants

.github/workflows/build.yml
- Leverage the `ramsey/composer-install@v1` GitHub Action step
- Remove builds for Composer v1 support (no longer guaranteed it is not made forbidden either)
- Add PHP 8.1 to the build
=> Simplify workflow

.github/workflows/lint.yml, phpstan.neon.dist, src/Autoload/ScoperAutoloadGenerator.php, vendor-bin/code-sniffer/composer.json, vendor-bin/code-sniffer/composer.lock, vendor-bin/phpstan/composer.json, vendor-bin/phpstan/composer.lock
- Upgrade CodeSniffer from 6.4.1 to 7.0.18
- Upgrade PHPStan from 0.12.99 to 1.3.3
- Execute the lint workflow on PHP 8.1
- Correct the lint workflow to install the necessary Composer dependencies within a dedicated step rather than inside the make command
=> Lint codebase on PHP 8.1

src/PhpParser/NodeVisitor/ClassAliasStmtAppender.php, src/PhpParser/NodeVisitor/ConstStmtReplacer.php, src/PhpParser/NodeVisitor/UseStmt/UseStmtPrefixer.php, src/PhpParser/TraverserFactory.php, src/Symbol/EnrichedReflector.php
The long-term goal is to completely split `Whitelist` into a Reflector and `SymbolsRegistry`. To this effect this new `EnrichedReflector` combines the reflective/expose API of `Whitelist` & `Reflector`. The goal with this new class is to consolidate the way excluded/exposed symbols are checked and provide a smoother API (only one service to check).
The current service is not complete yet however and to not introduce too abrupt changes it will be using both the Reflector and Whitelist underneath the hood for now.
=> Introduce the EnrichedReflector

src/Symbol/NamespaceRegistry.php, src/Whitelist.php, tests/Symbol/NamespaceRegistryTest.php
Introduce a new value object `NamespaceRegistry` which takes both namespace names and regexes and contain all the logic necessary for determining if a given symbol or namespace belongs to one of the registered namespaces.
=> Introduce NamespaceRegistry

src/RegexChecker.php, tests/RegexCheckerTest.php
`\Foo\A` is detected as a regex and whilst this is true (`\` used as a delimiter here with the flag `A`), it makes a lot of things complicated for an edge case which IMO has no reasons to be: if you wish such a regex simply use another delimiter.
=> Fix regex detection

composer.lock, src/PhpParser/NodeVisitor/NamespaceStmt/NamespaceStmtCollection.php, src/PhpParser/NodeVisitor/UseStmt/UseStmtCollection.php, tests/Console/Command/AddPrefixCommandTest.php
Closes #530; supports https://github.com/box-project/box/issues/562
This PR is not enough, but it's the foundation, of updating this package to work with PHP 8.1.
Other pieces:
Once those are fixed, we'll want to run `make test` and hope everything else works!
=> Update to support PHP 8.1

src/Configuration/ConfigurationFactory.php, src/Console/Command/AddPrefixCommand.php
The default file name of the config is not specific to the add-prefix command hence can be moved out. This allows for easier re-use like in #619.
=> Move default file name to the ConfigurationFactory

src/Autoload/ScoperAutoloadGenerator.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
=> Fix autoload generator links

specs/types/intersection.php, specs/types/union.php, src/PhpParser/NodeVisitor/NameStmtPrefixer.php
=> Add support for union and intersection types

tests/Scoper/PhpScoperTest.php
The CS fixer removes the trailing space found making the test fails.
=> Fix unstable test

src/Autoload/ScoperAutoloadGenerator.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
When there is several functions, having the 5 lines form is too verbose.
=> Make function alias delcarations one-liners

src/PhpParser/NodeVisitor/ClassAliasStmtAppender.php, src/PhpParser/TraverserFactory.php, src/Symbol/SymbolsRegistry.php, tests/Symbol/SymbolsRegistryTest.php
This makes the feature more reliable as avoid to have to keep synchronized the logic of when a symbol is aliased.
=> Use the recorded symbols to decide when to add the class_alias statements

docs/limitations.md
=> Add clarification on how to overcome some limitations

src/Console/Command/InspectSymbolCommand.php
Because we are not passing any path, the config loader tries to add all the paths of the current working directory and does so eagerly. To avoid that, we now pass a single file since the included/excluded file should not matter for the command result.
Closes #751
=> Fix InspectSymbol command slowness

src/Configuration/ConfigurationKeys.php
The `ConfigurationKeys` class cannot be made into an enum since we are using some entries as an array key which is not supported by enums.
=> Remove configuration keys todo

src/Configuration/SymbolsConfigurationFactory.php, tests/Configuration/SymbolsConfigurationFactoryTest.php
If the regex had the `i` flag it would have been appended still resulting in an invalid regex.
=> Fix regex cannot have the `i` flag

src/scoper.inc.php.tpl
=> Add example of excluded files collected with the Finder

.github/workflows/composer-root-version.yaml, .github/workflows/lint.yaml, Makefile
- Rename "Lint CS (8.1)" and "Lint PHPStan (8.1)" to respectively "CS" and "PHPStan".
- Fix PHP-CS-Fixer not being installed by ramsey/install
- Ensure the makefile targets are up to date in the CI before running the command.
- Rename "CS lint (8.1)" to "Lint CS"
=> ci: Review the Lint workflow

Makefile, composer-root-version-checker/Makefile, composer-root-version-checker/src/Checker.php
- Rename `update_root_version` and `check_composer_root_version` to respectively `composer_root_version_update` and `composer_root_version_lint`.
- Add a `composer_root_version_check` command that runs all the checks (previously `cd composer-root-version-checker; make all`).
- Rename ComposerRootVersionChecker make `all` command to `check` for consistency.
- Had to fiddle around with the order in order to satisfy some make variables being undefined.
=> chore: Tweak the ComposerRootVersionChecker related make commands

.gitignore
Those fixtures did not use to generate a lock file but it looks like under certain circumstances it now do (maybe just the new Composer version).
=> chore: Add undesired lock files to the gitignore

src/Autoload/ScoperAutoloadGenerator.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
=> Fixed scoper-autoload.php being incompatible with PHP 5

fixtures/set035-composer-files-autoload/index.php, fixtures/set035-composer-files-autoload/test.php
See #774 for the original test.
=> test: Refactor the e2e_035 test to clarify the desired behaviour

src/Console/ConsoleScoper.php
Related to https://github.com/humbug/php-scoper/issues/810
Hi,
I was facing the same issue after updating one of my package and doing local testings on a Windows mahcine. I've checked this fix locally and it's doing fine. I've used normalize instead of canonicalize as it's a bit faster and I don't think that weird paths like `to/../to/` are expected.
Tests workflow is green on my fork but I'm facing unexpected failure on E2E tests. I can't see why this commit could brain out PHAR generation. Let's see how this this PR performs 😸 
Feel free to close it if it's not welcome.
=> Normalize paths to avoid issue on Windows filesystems

phpstan.neon.dist, src/Console/Application.php, src/Console/Command/InspectCommand.php, tests/Console/Command/AddInspectCommandIntegrationTest.php, tests/Console/Command/AppIntegrationTest.php
This adds a command akin to `box process` which allows to output the scopped content of a singular file.
The command takes similar input as the `add-prefix` regarding the configuration and behaves identically except it will not try to execute the `init` command.
The scopped content can also be used as raw input by passing `--quiet`.
Closes #771.
=> feat: Add an inspect command

fixtures/set002/original/composer/installed.json, fixtures/set002/scoped/composer/installed.json, phpstan.neon.dist, src/Console/Command/AddPrefixCommand.php, src/Console/ConsoleScoper.php, src/Scoper/PhpScoper.php, src/Throwable/Exception/ParsingException.php, tests/Console/Command/AddPrefixCommandIntegrationTest.php, tests/Console/Command/AddPrefixCommandTest.php, tests/Scoper/PhpScoperTest.php
Closes #847.
As reported in #847, the current strategy is not ideal: if a failure occurs, the file is preserved. You can only see that there was a failure by paying attention to the output or having a more verbose output, unless you pass the `--stop-on-failure` option.
I think historically it has been that way because in the early days of PHP-Scoper, a failure was non infrequent and it was very frustrating to not be able to examine the result despite the failure.
The tool is now more robust and the only exception that I can see regularly coming still is invalid PHP code (e.g. when it is a template). As such, this PR proposes to:
- Leave the file unchanged if a PHP-Parser parsing error occurred (it is still marked as failed and appears in the logs as before).
- Fail on any other failure …
=> feat: Do not swallow exceptions when scoping

.php-cs-fixer.dist.php, res/create-scoper-phpstorm-stubs-map-patcher.php, res/get-scoper-phpstorm-stubs.php, scoper.inc.php
This is mostly for Box itself.
=> feat: Make the JetBrains' stubs collector and patcher re-usable

specs/misc/internal-declarations.php, src/Configuration/Configuration.php, src/Configuration/ConfigurationFactory.php, src/Configuration/ConfigurationKeys.php, src/PhpParser/NodeVisitor/InternalCommenter.php, src/PhpParser/TraverserFactory.php, src/Scoper/ScoperFactory.php, src/scoper.inc.php.tpl, tests/Configuration/ConfigurationFactoryTest.php, tests/Configuration/ConfigurationTest.php, tests/PhpParser/TraverserFactoryTest.php, tests/Scoper/PhpScoperSpecTest.php, tests/Scoper/PhpScoperTest.php, tests/Scoper/ScoperFactoryTest.php
This should allow IDEs such as PHPStorm to honour the tag and avoid showing the results in the auto-complete.
Closes #861.
=> feat: Mark all declarations as internal

.makefile/e2e.file, src/Autoload/ScoperAutoloadGenerator.php, tests/Autoload/AutoloadDumperTest.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
The dumped autoload should remain compatible with PHP 7.2.
=> fix: Fix the compatibility of the dumped autoload

docs/further-reading.md
There was a missing dash.
From #896
=> doc: Fix the broken link even more

composer.json, composer.lock, src/Configuration/ConfigurationFactory.php
- Drop support for Symfony 6 except the LTS version.
- Drop support for Symfony 5.
=> chore: Bump the minimum required Symfony version to 6.4

tests/Scoper/PhpScoperSpecTest.php
This `spec` keyword is not allowed within a specification file hence this condition can never be met.
=> test: Remove dead code

tests/Scoper/PhpScoperSpecTest.php, tests/Scoper/Spec/UnparsableFile.php
When a spec file could not be parsed, a `self::fail()` was used instead of letting the throwable bubble up. This was done to know which fail failed to parsed.
The implementation however, is faulty as if an exception is thrown, there is no stack trace. This is especially annoying when the throwable may not be thrown due to an invalid spec file but due to the way this file is parsed (i.e. code within the `PhpScoperSpecTest`).
This PR introduces a new exception which will contain the previously thrown exception but will also include a more friendly message to easily know for which file this was caused.
=> test: Do not hide the original throwable stack trace when failing to parse a file

tests/Scoper/Spec/Fixtures/complete-spec-file.php, tests/Scoper/Spec/Fixtures/simple-spec-file.php, tests/Scoper/Spec/SpecParser.php, tests/Scoper/Spec/SpecParserTest.php
This PR adds some tests for `SpecParser` as I noticed the implementation was accidentally skipping some tests. Note that a lot more tests could be added for checking the invalid keys and co, but this will be highly mitigated by #985.
=> test: Fix SpecParser accidentally skipping some tests

tests/Scoper/Spec/SpecPrinter.php, tests/Scoper/Spec/SpecPrinterTest.php, tests/Scoper/Spec/SpecScenario.php
- Rename it to `SpecPrinter`
- Passes the `SpecScenario` object for simplicitation
- Add tests
=> test: Tweak the SpecFormatter

docs/limitations.md, fixtures/set027-laravel/scoper.inc.php, specs/const/const-declaration-with-global-exposed.php, specs/const/const-declaration.php, specs/const/native-const.php, specs/func-declaration/global.php, specs/function/exposed-func-existence-checked.php, specs/function/namespace-global-scope-func.php, specs/function/native-func.php, specs/misc/date.php, specs/misc/expose-symbols-case-sensitiveness.php, specs/special-keywords/self-parent-return-type.php, specs/string-literal/misc.php, src/PhpParser/NodeVisitor/FunctionIdentifierRecorder.php, src/PhpParser/NodeVisitor/NameStmtPrefixer.php
Previously if a non-fully qualified symbol was matching an exposed or excluded one, PHP-Scoper assumed it matched. Technically this is wrong, but the assumption was still good for 99% of the cases.
However with #981, we no longer need this.
=> fix: Do not assume non-resolved symbols matches exposed or excluded symbols

composer.json, composer.lock
This is achieved by upgrading to `fidry/console` 0.6.10 which fixes https://github.com/theofidry/console/issues/221.
Indeed, PHP-Scoper does not use `symfony/deprecation-contracts` directly so it should be left as a transitive dependency.
Closes #939.
=> build(deps): Remove `symfony/deprecation-contracts` direct dependency

.makefile/e2e.file
This is an annoying class of issues as it is more likely to appear locally than in the CI.
=> test: Ensure the laravel e2e test cannot fail due to a color detection issue

tests/SpecFramework/SpecParser.php, tests/SpecFrameworkTest/SpecParserTest.php
This helps to navigate directly to the spec. Note however that if no title was given, no line number will be found. Maybe it is possible to find it still, but I don't think it is worth my efforts.
=> test: Add line numbers to the spec file

specs/string-literal/var.php, src/PhpParser/NodeVisitor/StringScalarPrefixer.php, src/Scoper/Symfony/XmlScoper.php, src/Scoper/Symfony/YamlScoper.php, tests/Scoper/Symfony/XmlScoperTest.php, tests/Scoper/Symfony/YamlScoperTest.php
=> fix: Do not scope class-like strings that cannot be class names

tests/SpecFrameworkTest/Fixtures/complete-spec-file.php, tests/SpecFrameworkTest/SpecParserTest.php, tests/SpecFrameworkTest/SpecPrinterTest.php
This is purely informative to avoid confusion
=> test: Fix the PHP version ID used

src/PhpParser/Printer/Printer.php, src/PhpParser/Printer/StandardPrinter.php
- Typehint against the interface instead of the abstract method.
- Correct the type for the old tokens.
=> refactor: Leverage the PhpParser v5 printer changes

src/Configuration/Configuration.php, src/Configuration/ConfigurationFactory.php, src/Configuration/ConfigurationKeys.php, src/Configuration/Throwable/InvalidConfiguration.php, src/Configuration/Throwable/InvalidConfigurationFile.php, src/Configuration/Throwable/InvalidConfigurationValue.php, src/Configuration/Throwable/UnknownConfigurationKey.php, src/Console/Command/AddPrefixCommand.php, src/Console/ConfigLoader.php, tests/Configuration/ConfigurationFactoryTest.php, tests/Configuration/ConfigurationTest.php, tests/Console/Command/AddPrefixCommandTest.php
Make the configuration and its factory throw more comprehensible exceptions. This also makes the switch from `InvalidArgumentException` to `UnexpectedValueException` which is more correct IMO as it is values provided by the user.
=> refactor: Throw more friendly exceptions when loading a configuration

docs/configuration.md, phpstan.neon.dist, src/PhpParser/Printer/StandardPrinterFactory.php
See the discussion in https://github.com/nikic/PHP-Parser/issues/1007.
This should fix https://github.com/sebastianbergmann/phpunit/issues/5855 although this may result in more ugly code formatting than desired. For this reason the default printer version is 7.2 rather than 5.3 as it would make the code too otherwise.
=> fix: Configure the printer PHP version to 7.2 by default

composer.json, composer.lock
Currently it is included via HumbugBox as a transitive dev deps but it is a required dependency for some commands like `inspect`.
=> fix: Fix missing var-dumper dependency

tests/AutoReview/GAE2ETest.php, tests/AutoReview/MakefileE2ETest.php
It looks like in some versions of PHPUnit the assert equal canonicalizing is not really taking care of the keys. I can't find the changelog about it though.
=> test: Fix e2e AutoReview test

src/Autoload/ScoperAutoloadGenerator.php, tests/AutoReview/GAE2ETest.php, tests/Autoload/ScoperAutoloadGeneratorTest.php
Hi @theofidry, I discovered a bug with the php-scoper.
Before the fix, I get
```
namespace Acme\Emca {
if (!function_exists('Acme\Emca\foo')) { function Emca\foo() { return \Humbug\Acme\Emca\foo(...func_get_args()); } }
}
```
which is crashing.
=> Fix function with multiple namespaces

.github/ISSUE_TEMPLATE/Bug_report.md, docs/configuration.md, docs/further-reading.md, src/scoper.inc.php.tpl
Solves #1097 
```php
use Isolated\Symfony\Component\Finder\Finder;
return [
'finders' => [
Finder::create()->files()->in('src'),
// ...
],
]
```
```php
/** @var Symfony\Component\Finder\Finder $finder */
$finder = Isolated\Symfony\Component\Finder\Finder::class;
return [
'finders' => [
$finder::create()->files()->in('src'),
// ...
],
]
```
A few unrelated (whitespace only) formatting things slipped through in this PR. An [.editorconfig](https://editorconfig.org/) or an automated lint step in a GitHub workflow would solve these kinds of issues and would make it easier for people to contribute to php-scoper. In my experience, an .editorconfig is usually enough.
=> feat: unlock intellisense for the finder component

docs/further-reading.md
**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update
**What is the current behavior?** (You can also link to an open issue here)
In the WordPress code example, lists of constants are assigned to `exclude-functions`, and lists of functions are assigned to `exclude-constants`. Also, there are typos: "Wordpress".
**What is the new behavior (if this is a feature change)?**
Correctly assign constants to `exclude-constants` and functions to `exclude-functions`. Change variable naming to camelCase as part of the Boy Scout rule.
Also, fix typos to "WordPress".
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
**Other …
=> Docs: Fix constant/function assignment in WP example

fixtures/set032-isolated-finder/expected-tree
I guess something changed within `tree`, not sure.
=> test: Fix e2e 032

specs/string-literal/new.php, src/PhpParser/NodeVisitor/StringScalarPrefixer.php
=> fix: Fix scoping of new statement with the new parent not being a name
