src/NodeVisitor/GroupUseNamespaceScoperNodeVisitor.php
src/NodeVisitor/ParentNodeVisitor.php
src/NodeVisitor/UseNamespaceScoperNodeVisitor.php
src/Scoper.php
src/functions.php
tests/ScoperTest.php

Rebased replacement of https://github.com/humbug/php-scoper/pull/26.

Fix PHP7 compatibility

---

src/Logger/ConsoleLogger.php
tests/Console/Command/AddPrefixCommandIntegrationTest.php

- Fix the progress bar to display correctly the number of items and the progress in percentage
- Always display the time and memory usage

Fix the progress bar

---

Makefile
src/Handler/HandleAddPrefix.php
src/Scoper.php
src/Scoper/ComposerScoper.php
src/Scoper/NullScoper.php
src/Scoper/PhpScoper.php
src/functions.php
tests/Handler/HandleAddPrefixTest.php
tests/PhpParser/FakeParser.php
tests/Scoper/ComposerScoperTest.php
tests/Scoper/FakeScoper.php
tests/Scoper/NullScoperTest.php
tests/Scoper/PhpScoperTest.php
tests/functions.php

Closes #46.
Right is at a state of a POC.
What is missing:
- Add tests
- Run `composer dump-autoload` after the scoping (I ran it manually for my tests)

Scope Composer autoloader

---

.gitignore
.travis.yml
Makefile
appveyor.yml
bin/php-scoper
fixtures/set004/bin/greet.php
fixtures/set004/box.json.dist
fixtures/set004/composer.json
fixtures/set004/expected-output
fixtures/set004/src/Greeter.php

Add e2e test

---

src/NodeVisitor/SingleLevelUseAliasVisitor.php
src/Scoper/PhpScoper.php
tests/Scoper/PhpScoperTest.php

Check if single level use statement is an aliased namespace, not simply a global namespace class

---

Makefile

Closes #48. FYI here's what we have right now:
https://blackfire.io/profiles/48ea61f2-d103-46a9-9f43-9ba5560c241d/graph

Add Blackfire profiling command

---

CONTRIBUTING.md
fixtures/set006/scoper.inc.php
fixtures/set009/scoper.inc.php
scoper.inc.php
src/Console/Command/AddPrefixCommand.php
src/Console/Configuration.php
src/Handler/HandleAddPrefix.php
src/NodeVisitor/FullyQualifiedNodeVisitor.php
src/NodeVisitor/GlobalWhitelistedNamesNodeVisitor.php
src/NodeVisitor/GroupUseNamespaceScoperNodeVisitor.php
src/NodeVisitor/IgnoreNamespaceScoperNodeVisitor.php
src/NodeVisitor/NamespaceScoperNodeVisitor.php
src/NodeVisitor/SingleLevelUseAliasVisitor.php
src/Scoper.php
src/Scoper/Composer/AutoloadPrefixer.php
src/Scoper/Composer/InstalledPackagesScoper.php
src/Scoper/Composer/JsonFileScoper.php
src/Scoper/NullScoper.php
src/Scoper/PatchScoper.php
src/Scoper/PhpScoper.php
tests/Console/Command/AddPrefixCommandIntegrationTest.php
tests/Console/Command/AddPrefixCommandTest.php
tests/Handler/HandleAddPrefixTest.php
tests/Scoper/Composer/InstalledPackagesScoperTest.php
tests/Scoper/Composer/JsonFileScoperTest.php
tests/Scoper/FakeScoper.php
tests/Scoper/NullScoperTest.php
tests/Scoper/PhpScoperTest.php
tests/functions.php

Scope whitelisted global namespace classes

---

.travis.yml
Makefile

Update Makefile rules to account for vendor-bin

---

README.md

@theofidry Updated the Readme in bits and pieces over the week, so given #86 might as well stash the draft to a PR for feedback.

[WIP] Update readme

---

specs/special-keywords/self-static-parent-method.php
src/NodeVisitor/NameStmtPrefixer.php

Fix usage of special keywords in a new statement

---

specs/misc.php
src/NodeVisitor/Collection/UseStmtCollection.php

Account for PHP case-insensitiveness

---

composer.json
composer.lock
src/Autoload/Requirements.php

Closes #150 and #141.
Thanks @firstred for the fix

Fix PHP version check

---

README.md

Update PHP-Scoper limitations

---

Makefile
composer.lock
fixtures/set016-symfony-finder/composer.json
fixtures/set016-symfony-finder/composer.lock
fixtures/set016-symfony-finder/expected-output
fixtures/set016-symfony-finder/main.php
fixtures/set017-symfony-di/composer.json
fixtures/set017-symfony-di/composer.lock
fixtures/set017-symfony-di/expected-output
fixtures/set017-symfony-di/main.php
fixtures/set018-nikic-parser/composer.json
fixtures/set018-nikic-parser/composer.lock
fixtures/set018-nikic-parser/expected-output
fixtures/set018-nikic-parser/main.php
fixtures/set019-symfony-console/composer.json
fixtures/set019-symfony-console/composer.lock
fixtures/set019-symfony-console/expected-output
fixtures/set019-symfony-console/main.php

Add a few popular projects to scope.

Add more e2e tests

---

src/Scoper/Composer/AutoloadPrefixer.php
tests/Scoper/Composer/JsonFileScoperTest.php

Do not add empty PSR-4 autoload entry

---

src/Configuration.php
src/Console/Command/AddPrefixCommand.php
src/Console/Command/InitCommand.php
tests/Console/Command/AddPrefixCommandTest.php

Add the prefix to the configuration

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_question.md
README.md

- Update the documentation regarding the usage with Box
- Update a few other elements
- Add GitHub templates

Update the documentation

---

composer.json
composer.lock
src/functions.php

I think solutions such as an auto-generated installer that could be created by Box or installing a
PHAR via phive is a better solution.

Remove self-update command

---

README.md
scoper.inc.php
src/Configuration.php
src/Console/Command/AddPrefixCommand.php
src/scoper.inc.php.tpl

Make the prefix configurable

---

src/Console/Command/AddPrefixCommand.php

Something that I learned recently :)

Destructure array in foreach loops

---

.gitignore
src/PhpParser/NodeVisitor/ConstStmtReplacer.php
src/PhpParser/NodeVisitor/NameStmtPrefixer.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php
src/Whitelist.php
tests/WhitelistTest.php

Fix whitelist case sensitiveness

---

.scrutinizer.yml
.travis.yml
composer.json
composer.lock
src/Autoload/ScoperAutoloadGenerator.php

- Disable xdebug
- Fix PHP-Scoper version to allow the newer versions of Box to be installed
- Fix Scrutinizer
- Bump the dependencies
- Ensure the dependencies are compatible for PHP 7.1.0

Fix the CI

---

.gitignore
box.json.dist
src/functions.php

Fix the version used in the PHAR

---

specs/string-literal/array-var.php
specs/string-literal/class-const-array.php
specs/string-literal/class-const.php
specs/string-literal/class-prop.php
specs/string-literal/class-var.php
specs/string-literal/const.php
specs/string-literal/define-value.php
specs/string-literal/func-arg.php
specs/string-literal/method-arg.php
specs/string-literal/new.php
specs/string-literal/var.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

Fix scoping of string literal classes which contains numbers

---

src/Console/ApplicationFactory.php
src/functions.php
tests/functions.php

This should be easier to consume PHP-Scoper as a package like done in Box.

Use an application factory

---

specs/string-literal/return.php.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

Fix the prefixing of returned string literals

---

src/Console/Command/AddPrefixCommand.php

Update the pattern that matches "vendor" directories to work on Windows.

 "vendor" directories matching pattern adjustment

---

vendor-bin/phpstan/composer.json
vendor-bin/phpstan/composer.lock

This did not introduce any new 'faults' for this project

Upgrade phpstan to 11.8

---

vendor-bin/code-sniffer/composer.json
vendor-bin/code-sniffer/composer.lock

This did not change any observable behaviour for this project.

Upgrade coding standards to their latest versions

---

README.md

Document PSR-0 limitations

---

box.json.dist

Fix invalid version in the PHAR

---

specs/class/typed-properties.php
specs/exp/coalescing-assignment.php
specs/func-arrow/global-scope-arrow-func.php
specs/func-arrow/namespace-arrow-func-with-use-stmt.php
specs/func-arrow/namespace-arrow-func.php
src/PhpParser/NodeVisitor/NameStmtPrefixer.php
src/Reflector.php

- Add support for arrow functions
- Add support for typed properties
- Ensure the new functions are included in the Reflector

Add support for PHP 7.4 new features

---

psysh.php
specs/misc/internal-symbols.php
specs/string-literal/func-arg.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

Fix string resolution with leading backslas

---

.travis.yml
Makefile
fixtures/set006/scoper.inc.php
fixtures/set018-nikic-parser/scoper.inc.php
fixtures/set032-isolated-finder/expected-tree
fixtures/set032-isolated-finder/scoper.inc.php

Add e2e test to ensure the isolated finder exists

---

src/Scoper/Symfony/XmlScoper.php
src/Scoper/Symfony/YamlScoper.php
tests/Scoper/Symfony/XmlScoperTest.php
tests/Scoper/Symfony/YamlScoperTest.php

Fix scoping of PSR-4 locator services

---

specs/function/global-scope-global-func-with-single-level-use-statement.php
specs/function/global-scope-global-func.php
src/Reflector.php
tests/ReflectorTest.php

Closes #365
@Wouter0100 could you confirm this solves your issue?

Handle functions as case-insensitive names

---

README.md

docs: add WordPress limitation section (#303)

---

specs/use/use-class-group.php
specs/use/use-const-group.php
specs/use/use-func-group.php
specs/use/use-mix-group.php
src/PhpParser/NodeVisitor/UseStmt/UseStmtCollection.php

See https://github.com/nikic/PHP-Parser/blob/f66a32e2df7866d593fa7a1bb582348f772511b0/lib/PhpParser/Node/Stmt/Use_.php#L9-L14
Need check `type` both `$use_` and `$useStatement`.
Fixes box-project/box#476

Fix group use bug

---

Makefile

The intend is to refresh the timestamp not creating the file

[Makefile] Do not create file with touch

---

Makefile
README.md
vendor-bin/phpstan/composer.json
vendor-bin/phpstan/composer.lock

* Fix PHPStan in Makefile
* Upgrade PHPStan to 0.12.57
* Update build status badges

 Fix PHPStan in Makefile

---

.composer-root-version
.scrutinizer.yml
composer.json
composer.lock

waits for https://github.com/box-project/box/pull/517

update box to version 3.11 and bump composer root version to 0.14.99

---

specs/special-keywords/self-parent-return-type.php
src/PhpParser/NodeVisitor/NameStmtPrefixer.php

parent return type

---

composer.lock

Upgrade nikic/php-parser to v4.10.5

---

_specs/unicode-string.php
specs/unicode-string.php

Provide a failing test case of #464

Unicode Entities reproducer

---

src/Console/Application.php
src/Console/Command/AddPrefixCommand.php
src/Console/Command/ChangeableDirectory.php
src/Console/ConfigLoader.php
src/Console/ConsoleScoper.php
src/Console/ScoperLogger.php
tests/Console/Command/AddPrefixCommandTest.php

No change of logic, pure refactoring to make it easier to follow

Refactor AddPrefixCommand

---

specs/ConfigurationTest.php
src/Configuration.php
src/ConfigurationFactory.php

Move Prefix validation to the Configuration class

---

src/Configuration.php
src/ConfigurationFactory.php
tests/ConfigurationTest.php

Fix a few issues introduced in #489: a bit too quick of a merge

Fix prefix validation

---

specs/class/typed-properties.php
src/PhpParser/NodeVisitor/NameStmtPrefixer.php

Fix scoping of typed properties

---

src/PhpParser/NodeVisitor/ClassIdentifierRecorder.php
src/PhpParser/NodeVisitor/ConstStmtReplacer.php
src/PhpParser/NodeVisitor/NamespaceStmt/FunctionIdentifierRecorder.php
src/PhpParser/NodeVisitor/ParentNodeAppender.php
src/PhpParser/NodeVisitor/Resolver/IdentifierResolver.php
src/PhpParser/TraverserFactory.php
tests/Scoper/PhpScoperSpecTest.php

Replaces a number of usages of the now deprecated FullyQualifiedNameResolver by IdentifierResolver

Introduce IdentifierResolver and make use of it

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/tests.yml

- Split the current "build" workflow into two: "build" and "tests"
- Tidy up the "lint" build

Tweak workflow

---

vendor-bin/covers-validator/composer.lock

Update covers validator from v1.3.1 to v1.4.0

Update covers validator

---

src/PhpParser/NodeVisitor/UseStmt/UseStmtPrefixer.php

Minor changes with the introduction of `isExposedConstant()` which better matches the future desired API.

Review UseStmtPrefixer

---

specs/class/anonymous.php
src/PhpParser/NodeVisitor/ClassAliasStmtAppender.php

Minor changes with the introduction of `isExposedClass()` which better matches the future desired API.

Review ClassAliasStmtAppender

---

src/RegexChecker.php
tests/RegexCheckerTest.php

Restrict regex delimiters allowed

---

src/Configuration/Configuration.php
src/Configuration/ConfigurationFactory.php
src/Console/Command/AddPrefixCommand.php
src/Console/Command/InspectSymbolCommand.php
src/Console/ConfigLoader.php
src/Console/ConsoleScoper.php
tests/Console/Command/AddPrefixCommandIntegrationTest.php
tests/Console/Command/AddPrefixCommandTest.php

Stops the process if says no when PHP-Scoper asks if the output directory can be deleted

Adjust AddPrefixCommand and Configuration

---

src/Configuration/Configuration.php
src/PhpParser/Node/PrefixedName.php
tests/Configuration/ConfigurationTest.php

Add Configuration::withPrefix()

---

Makefile
fixtures/set004/composer.lock
fixtures/set014/composer.lock

This is purely for maintaining purpose to have a quick glance at which fixtures contains outdated deps

Add outdated-fixtures command

---

src/Container.php
src/PhpParser/Printer/Printer.php
src/PhpParser/Printer/StandardPrinter.php
src/Scoper/PhpScoper.php
src/Scoper/ScoperFactory.php
tests/Console/Command/AddPrefixCommandTest.php
tests/Console/Command/AppIntegrationTest.php
tests/Console/Command/DummyScoperFactory.php
tests/PhpParser/FakePrinter.php
tests/PhpParser/TraverserFactoryTest.php
tests/Scoper/PhpScoperSpecTest.php
tests/Scoper/PhpScoperTest.php
tests/Scoper/ScoperFactoryTest.php

Introduce a Printer abstraction

---

composer.lock

Fix Console symlink issue

---

.github/workflows/security.yaml

Add a build to check dependencies

---

src/Patcher/PatcherChain.php

Unmark PatcherChain#getPatchers as internal

---

src/Symbol/SymbolRegistry.php
tests/Symbol/SymbolRegistryTest.php

Don't allow empty string as a symbol regex or name

---

scoper.inc.php
src/PhpParser/NodeVisitor/NameStmtPrefixer.php

Simplify the isolated finder config

---

specs/const/const-declaration.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

Fix define check of class constant

---

specs/use/use-trait.php

Add regression test for trait import

---

fixtures/set002/original/executable-file.php
fixtures/set002/scoped/executable-file.php
src/Console/ConsoleScoper.php
tests/Console/Command/AddPrefixCommandIntegrationTest.php
tests/Console/Command/AddPrefixCommandTest.php

Preserve the files permissions

---

src/Configuration/SymbolsConfigurationFactory.php
tests/Configuration/SymbolsConfigurationFactoryTest.php

- Extract retrieving the regex into a dedicated method
- Remove unused method
- Rename test case to match the tested class name

Refactor SymbolsConfigurationFactory

---

src/Symbol/EnrichedReflector.php

The statements should all be strictly equivalent, there is no logic change here.

Refactor EnrichedReflector methods

---

.github/workflows/release.yaml

In-line the PHP version to not have the workflow name changing everytime we update update the PHP version.

ci: Simplify the build workflow

---

README.md

doc: Fix the PHP-Scoper integration link

---

composer-root-version-checker/src/CouldNotParseTag.php
composer-root-version-checker/src/Logger.php
src/Autoload/ScoperAutoloadGenerator.php
src/Configuration/Configuration.php
src/Scoper/Composer/AutoloadPrefixer.php
tests/Console/Command/AddPrefixCommandIntegrationTest.php
tests/FunctionsTest.php
tests/Scoper/PhpScoperSpecTest.php
tests/Symbol/SymbolsRegistryTest.php
vendor-bin/php-cs-fixer/composer.json
vendor-bin/php-cs-fixer/composer.lock

- Update `friendsofphp/php-cs-fixer` from `3.13.0` to `3.35.1`.
- Migrate from `theofidry/php-cs-fixer-config` to `fidry/php-cs-fixer-config`.

style: Upgrade PHP-CS-Fixer

---

.github/workflows/release.yaml
Dockerfile
docs/installation.md

build: Add a docker image

---

README.md
docs/further-reading.md
res/create-symfony-php-services-patcher.php
tests/Patcher/SymfonyPhpServicesPatcherTest.php

fix: Fix Symfony services

---

specs/string-literal/func-arg-is-callable.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

fix: Correctly scope is_callable() calls

---

specs/string-literal/func-arg-call-user-func.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

fix: Correctly scope call_user_func_array()

---

.github/workflows/composer-root-version.yaml

There was a typo in the condition.

ci: Fix ComposerRootVersion workflow logic

---

.makefile/e2e.file

Fix a typo

---

.github/workflows/release.yaml

See https://github.com/softprops/action-gh-release#permissions.

ci: Allow write permissions for the release workflow

---

bin/php-scoper
composer-root-version-checker/src/CouldNotParseTag.php
rector.php
vendor-bin/php-cs-fixer/composer.lock

Upgrade from v3.35.1 to v3.53.0.

build: Upgrade PHP-CS-Fixer

---

phpunit.xml.dist

test: Remove the NO_COLOR environment variable

---

README.md
docs/configuration.md

docs: Add mention of the inspect commmand

---

fixtures/set040-polyfills/bootstrap.php
specs/func-declaration/excluded.php
specs/func-declaration/global.php
src/PhpParser/NodeVisitor/ExcludedFunctionExistsEnricher.php
src/PhpParser/NodeVisitor/ExcludedFunctionExistsStringNodeStack.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php
src/PhpParser/TraverserFactory.php

Not an ideal title but hopefully the problem is described well enough in #963 and the tests are explicit too.
Closes #963.

fix: Add an additional function_exists statement for excluded function checks

---

tests/Scoper/PhpScoperSpecTest.php

This is to reduce the noise in #985.

cs: Change the CS of parseSpecFile to reduce noise

---

specs/string-literal/func-arg-class-func.php
src/PhpParser/NodeVisitor/StringScalarPrefixer.php

fix: Handle arguments of method_exists
